version: 1.0-{build}
build_script:
- cmd: >-
    appveyor_build.bat
on_failure:
- 7z a -mx9 -r fail.7z *.exe *.sln *.txt *.log
- appveyor.exe PushArtifact fail.7z
shallow_clone: true
test: off
artifacts:
- path: sendinput_x64.exe
- path: sendinput_x86.exe
- path: sendinput_io_x64.exe
- path: sendinput_io_x86.exe
- path: sendinput.7z
cache:
  - tests
skip_commits:
  files:
    - 'LICENSE'
    - '*.md'
    - '.gitingore'
    - '.gitattributes'
deploy:
- provider: Environment
  name: github
  on:
    appveyor_repo_tag: true
