version: 1.0.{build}
configuration:
- Release
- MinSizeRel
build_script:
- cmd: >-
    mkdir Build

    C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\\Build\" && exec cmake .. -G \"MSYS Makefiles\" -DCMAKE_C_FLAGS=-s -Wdev -Wdeprecated"

    C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\\Build\" && exec make"

    7z a -mx9 -r binary.7z *.exe

    7z a -mx9 -r all.7z *.*
artifacts:
- path: binary.7z
- path: all.7z
test: off
